{% set n = noOfNodes | int %}

version: '3.6'

services:

  party{{n}}:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party{{n}}
    ports:
      - "1000{{3*n+3}}:10201"
      - "222{{n}}:2222"
    volumes:
      - ./party{{n}}/node.conf:/etc/corda/node.conf
      - ./party{{n}}/certificates:/opt/corda/certificates
      - ./party{{n}}/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

