

version: '3.6'

services:

  party1:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party1
    ports:
      - "10006:10201"
      - "2221:2222"
    network_mode: host
    volumes:
      - ./party1/node.conf:/etc/corda/node.conf
      - ./party1/certificates:/opt/corda/certificates
      - ./party1/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

