
version: '3.6'

services:

  party3:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party3
    ports:
      - "20005:10301"
      - "2220:2222"
    network_mode: host
    volumes:
      - ./party3/node.conf:/etc/corda/node.conf
      - ./party3/certificates:/opt/corda/certificates
      - ./party3/persistence:/opt/corda/persistence
      - ./party3/cordapps:/opt/corda/cordapps
