{% set noOfNodes = noOfNodes | int %}
{% set noOfNotary = noOfNotary | int %}

version: '3.6'

services:
{% for n in range(noOfNotary) %}
  notary{{n}}:
    image: corda/corda-zulu-java1.8-4.5
    container_name: notary{{n}}
    network_mode: host
    ports:
      - "2000{{3*n+3}}:10201"
    volumes:
      - ./notary{{n}}/node.conf:/etc/corda/node.conf
      - ./notary{{n}}/certificates:/opt/corda/certificates
      - ./notary{{n}}/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
{% endfor %}

{% for n in range(noOfNodes) %}
  party{{n}}:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party{{n}}
    network_mode: host
    ports:
      - "1000{{3*n+3}}:10201"
      - "222{{n}}:2222"
    volumes:
      - ./party{{n}}/node.conf:/etc/corda/node.conf
      - ./party{{n}}/certificates:/opt/corda/certificates
      - ./party{{n}}/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
{% endfor %}
