


version: '3.6'

services:


  0:
    image: corda/corda-zulu-java1.8-4.5
    container_name: {nodename}
    network_mode: host
    ports:
      - "20003:10201"
    volumes:
      - ./{nodename}/node.conf:/etc/corda/node.conf
      - ./{nodename}/certificates:/opt/corda/certificates
      - ./{nodename}/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

