

version: '3.6'

services:

  notary1:
    image: corda/corda-zulu-java1.8-4.5
    container_name: notary1
    network_mode: host
    ports:
      - "20006:10201"
    volumes:
      - ./notary1/node.conf:/etc/corda/node.conf
      - ./notary1/certificates:/opt/corda/certificates
      - ./notary1/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

