

version: '3.6'

services:

  notary2:
    image: corda/corda-zulu-java1.8-4.5
    container_name: notary2
    ports:
      - "20009:10201"
    network_mode: host
    volumes:
      - ./notary2/node.conf:/etc/corda/node.conf
      - ./notary2/certificates:/opt/corda/certificates
      - ./notary2/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

