


version: '3.6'

services:



  party0:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party0
    ports:
      - "10003:10201"
      - "2221:2222"
    volumes:
      - ./party0/node.conf:/etc/corda/node.conf
      - ./party0/certificates:/opt/corda/certificates
      - ./party0/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters

