


version: '3.6'

services:

  notary0:
    image: corda/corda-zulu-java1.8-4.5
    container_name: notary0
    network_mode: host
    ports:
      - "20003:10201"
    volumes:
      - ./notary0/node.conf:/etc/corda/node.conf
      - ./notary0/certificates:/opt/corda/certificates
      - ./notary0/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps



  party0:
    image: corda/corda-zulu-java1.8-4.5
    container_name: party0
    network_mode: host
    ports:
      - "10003:10201"
      - "2220:2222"
    volumes:
      - ./party0/node.conf:/etc/corda/node.conf
      - ./party0/certificates:/opt/corda/certificates
      - ./party0/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps

